apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  USER_SERVICE_URL: "http://user-service.dev.svc.cluster.local"
  ORDER_SERVICE_URL: "http://order-service.dev.svc.cluster.local"
  ENV: "dev"